### ISSUE TITLE
"Auth0 account is not specified" with knpuniversity/oauth2-client-bundle

### ISSUE THREAD

**Issue by picks44** [RiskioFr/oauth2-auth0#3]
Hello,

I'm trying to connect through Auth0, but I get the error  `Auth0 account is not specified` from this bundle when I try to reach `/connect/auth0` route.

What is wrong ?

My setup is the following (Symfony 3.4)
```
knpu_oauth2_client:
    clients:
        auth0:
            type: auth0
            client_id: '%auth0_client_id%' (in parameters.yml)
            client_secret: '%auth0_client_secret%' (in parameters.yml)
            redirect_route: connect_auth0_check
            redirect_params: {}
```

```
    /**
     * @Route("/connect/auth0")
     *
     * @return \Symfony\Component\HttpFoundation\RedirectResponse
     * @throws \InvalidArgumentException
     */
    public function connectAction()
    {
        return $this->get('oauth2.registry')
            ->getClient('auth0')
            ->redirect();
    }

    /**
     * @Route("/connect/auth0/check", name="connect_auth0_check")
     *
     * @param Request $request
     * @throws \InvalidArgumentException
     */
    public function connectCheckAction(Request $request)
    {
        $client = $this->get('oauth2.registry')
            ->getClient('auth0');

        try {
            $user = $client->fetchUser();
            var_dump($user->getName());
        } catch (IdentityProviderException $e) {
            var_dump($e->getMessage());die;
        }
    }
```

**Comment by neeckeloo** [comment]
Sorry for the delayed response. You have to specify your account name in order to define your custom domain. For that, you have to add account parameter to your configuration :

```yaml
knpu_oauth2_client:
    clients:
        auth0:
            type: auth0
            account: '%account%' (in parameters.yml)
            ...
```

I will add this missing information in the README file.
